# The book's title. Will be used everywhere!
title: "is to with but your are on not for get you your they can one with for was do if get can it to one not you it out at just u up in but at we when they out do a up when we out find not have your all one when for this was find so this have I so out are of it not my my with can so we u your to is be we out be it do when get was out for do your of so that was one on they we we this on with  me are it out one with out find its that u out so for that find do  so its at me we not one of one we so they be on one my for but but on it out up but and if a when your if your get we its find be if but out for u but this out all this me just find can can they it all we find u on just on at they out a they one do in"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2014 by John Doe.
#   Copyright 2014 by John Doe. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#
#
copyright: "No Copyright"

# Who's publishing this book.
publisher: "Cole Willsea"

# When this book was published.
published_at: "2014-09-01"

# Some book description.
subject: "A collection of haikus found by @haiku_ebooks on twitter. Haikus are easy / Five then seven then five more / George Bush is racist | by @JohnLodi"

# Some keywords that identify this book.
keywords: "haiku, poetry, twitter, net-art, art, robots"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "http://coleww.github.io/haiku_chapbooks/"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://coleww.github.io/haiku_chapbooks/"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Haiku eBooks"

# The base URL from your source code.
base_url: http://colewillsea.com
